### ISSUE TITLE
S3 API access permissions issue

### ISSUE THREAD

**Issue by ChandrakanthSenadhipaytam** [dssc1/eventBridgeCodeBuild#1]
Following cmd gives error on copy,need code fix..

 aws s3 cp Code/manifest10.json s3://S3_BUCKET
upload failed: Code/manifest10.json to s3://S3_BUCKET/manifest10.json An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

**Comment by SridharChevendra** [comment]
Ensure the role attached to the cloud9 IDE or EC2 has appropriate policies attached. Alternatively, upload the files from the console.
